runtime: nodejs14
api_version: 1

handlers:
- url: /
  static_files: site/public/index.html
  upload: site/public/index.html
  secure: always

- url: /(.*)
  static_files: site/public/\1
  upload: site/public/(.*)
